trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    echo "##vso[task.prependpath]/usr/local/bin"
  displayName: 'Add /usr/local/bin to PATH'

- script: |
    # Initialize Terraform
    terraform init
    # Plan Terraform changes
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    # Apply Terraform changes
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'

- script: |
    # (Optional) Destroy Terraform resources
    # terraform destroy -auto-approve
  displayName: 'Terraform Destroy'

- task: Docker@2
  inputs:
    containerRegistry: 'pipe-docker'  # Use your Docker registry connection name
    repository: 'sakshisawalikar16/terraform'  # Use your image repository name
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: 'Build Docker Image'
