trigger:
- main  # Replace with your branch name or trigger condition

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate agent image

steps:
- script: echo 'This is your build step.'  # Replace with actual build steps
  displayName: 'Build Docker Image'

- task: Docker@2
  inputs:
    containerRegistry: 'pipe-docker'
    repository: 'sakshisawalikar16 / terraform'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
